"""M1-P2 SP package (P2A/P2B/P2C algorithms plus the P2D facade)."""

from .beats import BeatAnalysis, BeatCandidate, BeatDetector, BeatSegment, BeatSegmenter, analyze_beats
from .errors import SPError
from .filters import CausalFIRFilter, FilterBank, FilteredSeries, OfflineReviewFilter, design_lowpass_fir
from .integrity import IntegrityAnalyzer
from .metrics import RawQualityMetrics
from .engineering_units import (
    EngineeringUnitConversionProvenance,
    EngineeringUnitConversionStatus,
    EngineeringUnitConverter,
    EngineeringUnitValue,
    RawIdentityConverter,
    SyntheticCalibrationAdapter,
)
from .models import (
    BeatReferenceBundle,
    IntegrityAnalysis,
    IntegrityConsistency,
    NormalizedChannelSeries,
    NormalizedSession,
    ProcessingEvidence,
    QualityEvaluation,
    QualityMetricsInternal,
    SPPreprocessResult,
    SPProcessingProvenance,
    SPProcessingResult,
    SPQualityStageResult,
    StableWindow,
    StableWindowResult,
)
from .normalization import InputNormalizer
from .observations import SequenceObservations, TimestampObservations, observe_sequence, observe_timestamps
from .parameters import (
    METRIC_FORMULA_VERSIONS,
    P2A_CONFIGURATION_DIGEST,
    P2B_CHARACTERIZATION_SEEDS,
    P2B_CONFIGURATION_DIGEST,
    P2C_CHARACTERIZATION_SEEDS,
    P2C_CONFIGURATION_DIGEST,
    SP_PARAMETER_VERSION,
    SP_PARAMETER_VERSION_P2A,
    SP_PARAMETER_VERSION_P2B,
    SP_PARAMETER_VERSION_P2C,
    SP_PROCESSING_VERSION,
    SP_PROCESSING_VERSION_P2A,
    SP_PROCESSING_VERSION_P2B,
    SP_PROCESSING_VERSION_P2C,
    SPParameter,
    SPParameterClass,
    SPParameterSet,
    default_p2a_parameter_set,
    default_p2b_parameter_set,
    default_p2c_parameter_set,
)
from .processor import (
    SP_PROCESSING_VERSION_P2D,
    SPPreprocessor,
    SPProcessor,
    SPQualityProcessor,
    create_p2c_processor,
    create_p2d_processor,
)
from .projection import M1QualityProjector
from .quality import (
    PROCESSING_STATUS_BLOCKED,
    PROCESSING_STATUS_EVALUATED,
    QualityEvaluator,
    sort_reason_codes,
)
from .reference import PPGDetector, ReferenceAligner, ReferenceMatchSummary, analyze_reference
from .summary import (
    canonical_json_bytes,
    compare_sp_results,
    sp_result_fingerprint,
    sp_result_sha256,
    summarize_sp_result,
)
from .windows import StableWindowSelector

__all__ = [
    "SPError",
    "METRIC_FORMULA_VERSIONS",
    "P2A_CONFIGURATION_DIGEST",
    "P2B_CHARACTERIZATION_SEEDS",
    "P2B_CONFIGURATION_DIGEST",
    "P2C_CHARACTERIZATION_SEEDS",
    "P2C_CONFIGURATION_DIGEST",
    "SP_PARAMETER_VERSION",
    "SP_PARAMETER_VERSION_P2A",
    "SP_PARAMETER_VERSION_P2B",
    "SP_PARAMETER_VERSION_P2C",
    "SP_PROCESSING_VERSION",
    "SP_PROCESSING_VERSION_P2A",
    "SP_PROCESSING_VERSION_P2B",
    "SP_PROCESSING_VERSION_P2C",
    "SP_PROCESSING_VERSION_P2D",
    "BeatAnalysis",
    "BeatCandidate",
    "BeatDetector",
    "BeatReferenceBundle",
    "BeatSegment",
    "BeatSegmenter",
    "CausalFIRFilter",
    "EngineeringUnitConversionProvenance",
    "EngineeringUnitConversionStatus",
    "EngineeringUnitConverter",
    "EngineeringUnitValue",
    "FilterBank",
    "FilteredSeries",
    "InputNormalizer",
    "IntegrityAnalysis",
    "IntegrityAnalyzer",
    "IntegrityConsistency",
    "M1QualityProjector",
    "NormalizedChannelSeries",
    "NormalizedSession",
    "OfflineReviewFilter",
    "PROCESSING_STATUS_BLOCKED",
    "PROCESSING_STATUS_EVALUATED",
    "PPGDetector",
    "ProcessingEvidence",
    "QualityEvaluation",
    "QualityEvaluator",
    "QualityMetricsInternal",
    "RawIdentityConverter",
    "RawQualityMetrics",
    "ReferenceAligner",
    "ReferenceMatchSummary",
    "SequenceObservations",
    "TimestampObservations",
    "observe_sequence",
    "observe_timestamps",
    "SPParameter",
    "SPParameterClass",
    "SPParameterSet",
    "SPPreprocessResult",
    "SPProcessingProvenance",
    "SPProcessingResult",
    "SPProcessor",
    "SPPreprocessor",
    "SPQualityProcessor",
    "SPQualityStageResult",
    "StableWindow",
    "StableWindowResult",
    "StableWindowSelector",
    "SyntheticCalibrationAdapter",
    "analyze_beats",
    "analyze_reference",
    "canonical_json_bytes",
    "compare_sp_results",
    "create_p2c_processor",
    "create_p2d_processor",
    "default_p2a_parameter_set",
    "default_p2b_parameter_set",
    "default_p2c_parameter_set",
    "design_lowpass_fir",
    "sort_reason_codes",
    "sp_result_fingerprint",
    "sp_result_sha256",
    "summarize_sp_result",
]
