import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

type Step={target_force:number;sample_count:number;quality_label:string;quality_score:number;heart_rate_bpm:number|null;pulse_amplitude:number|null};
type Result={manifest:{session_id:string;statistics:{frame_count:number;missing_frame_count:number;crc_error_count:number}};report:{analysis_allowed:boolean;best_target_force:number|null;steps:Step[];disclaimer:string}};
type D2Step={step_index:number;target_force_au:number;quality_label:string;stable_sample_count:number;score:number|null};
type D2Report={analysis_allowed:boolean;best_target_force_au:number|null;calibration_id:string;report_sha256:string;steps:D2Step[];disclaimer:string};
type D3Event={case_id:string;event_tick:number;fault:string;action:string;state:string;detection_latency_ticks:number;command:number;detected_faults:string[]};
type D3Report={report_sha256:string;model_units:string;medical_use:boolean;analysis_allowed:boolean;summary:{case_count:number;passed_count:number;failed_count:number;all_passed:boolean};events:D3Event[];limitations:string[];disclaimer:string};
type RuntimeEvent={tick:number;type:string;state?:string;command?:number;code?:string;action?:string};
type RuntimeSnap={run_id:string;status:string;state:string;tick:number;target_force_au:number|null;actual_force_au:number;position_au:number;command:number;unload_complete:boolean;final_state:string|null;error:string|null;seed:number;targets_au:number[];timeline:{tick:number;state:string}[];events:RuntimeEvent[];report:Record<string,unknown>|null;disclaimer:string};

const ABORTABLE=new Set(['APPROACH','CONTACT','STABILIZE','ACQUIRE','STEP']);

function App(){
 const [health,setHealth]=useState('检查中'); const [device,setDevice]=useState('握手中'); const [d3,setD3]=useState<D3Report|null>(null); const [d3Busy,setD3Busy]=useState(false); const [replayState,setReplayState]=useState('尚未重放'); const [result,setResult]=useState<Result|null>(null); const [d2,setD2]=useState<D2Report|null>(null); const [busy,setBusy]=useState(false); const [d2Busy,setD2Busy]=useState(false); const [error,setError]=useState(''); const [wave,setWave]=useState<number[]>([]); const [force,setForce]=useState<number[]>([]);
 const [runtime,setRuntime]=useState<RuntimeSnap|null>(null); const [runtimeBusy,setRuntimeBusy]=useState(false); const [abortBusy,setAbortBusy]=useState(false); const pollRef=useRef<number|null>(null);
 useEffect(()=>{
  fetch('/api/health').then(r=>r.json()).then(x=>setHealth(`${x.stage}服务正常`)).catch(()=>setHealth('服务未连接'));
  fetch('/api/device/d1-demo?fragment_size=5').then(r=>r.json()).then(x=>{
   const ready=x.connected&&x.exchanges.every((e:{status:string})=>e.status==='ACK');
   setDevice(ready?'虚拟设备已握手':'设备协议异常');
  }).catch(()=>setDevice('虚拟设备未连接'));
  return ()=>{if(pollRef.current!==null)window.clearInterval(pollRef.current);};
 },[]);
 function stopPoll(){if(pollRef.current!==null){window.clearInterval(pollRef.current);pollRef.current=null;}}
 function startPoll(runId:string){stopPoll();pollRef.current=window.setInterval(()=>{fetch(`/api/experiments/d3/runs/${runId}`).then(r=>{if(!r.ok)throw new Error(`运行查询失败：${r.status}`);return r.json();}).then((snap:RuntimeSnap)=>{setRuntime(snap);if(['COMPLETED','ABORTED_IDLE','FAILED','FAULT_LATCHED'].includes(snap.status)){stopPoll();setRuntimeBusy(false);}}).catch(e=>{setError(e.message);stopPoll();setRuntimeBusy(false);});},200);}
 function run(){setBusy(true);setError('');setResult(null);setWave([]);setForce([]);const scheme=location.protocol==='https:'?'wss':'ws';const ws=new WebSocket(`${scheme}://${location.host}/ws/simulate`);ws.onopen=()=>ws.send(JSON.stringify({sample_rate_hz:250,heart_rate_bpm:72,target_forces:[40,80,120],stabilize_s:.8,acquire_s:5}));ws.onmessage=(event)=>{const message=JSON.parse(event.data);if(message.type==='samples'){setWave(v=>[...v,...message.data.map((x:{pulse:number})=>x.pulse)].slice(-300));setForce(v=>[...v,...message.data.map((x:{force:number})=>x.force)].slice(-300));}if(message.type==='complete'){setResult({manifest:message.manifest,report:message.report});setBusy(false);}if(message.type==='error'){setError(message.message);setBusy(false);}};ws.onerror=()=>{setError('实时连接失败');setBusy(false);};}
 function runD3(){setD3Busy(true);setError('');setReplayState('尚未重放');fetch('/api/experiments/d3/run',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(r=>{if(!r.ok)throw new Error(`D3请求失败：${r.status}`);return r.json()}).then(x=>setD3(x)).catch(e=>setError(e.message)).finally(()=>setD3Busy(false));}
 function replayD3(){if(!d3)return;setReplayState('重放中…');fetch(`/api/experiments/d3/${d3.report_sha256}/replay`,{method:'POST'}).then(r=>{if(!r.ok)throw new Error(`重放失败：${r.status}`);return r.json()}).then(x=>setReplayState(x.identical?'逐字段与哈希一致':'重放不一致')).catch(e=>{setReplayState('重放失败');setError(e.message)});}
 function runD2(){setD2Busy(true);setError('');fetch('/api/experiments/d2/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target_forces_au:[40,80,120],sample_rate_hz:250,seed:20260805})}).then(r=>{if(!r.ok)throw new Error(`D2请求失败：${r.status}`);return r.json()}).then(x=>setD2(x)).catch(e=>setError(e.message)).finally(()=>setD2Busy(false));}
 function startRuntime(){setRuntimeBusy(true);setError('');setRuntime(null);stopPoll();fetch('/api/experiments/d3/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targets_au:[20,40,60],seed:20260805,hold:true,max_duration_s:120})}).then(r=>{if(!r.ok)throw new Error(`启动运行失败：${r.status}`);return r.json();}).then((snap:RuntimeSnap)=>{setRuntime(snap);startPoll(snap.run_id);}).catch(e=>{setError(e.message);setRuntimeBusy(false);});}
 function abortRuntime(){if(!runtime)return;setAbortBusy(true);setError('');fetch(`/api/experiments/d3/runs/${runtime.run_id}/abort`,{method:'POST'}).then(r=>{if(!r.ok)throw new Error(`ABORT失败：${r.status}`);return r.json();}).then((snap:RuntimeSnap)=>setRuntime(snap)).catch(e=>setError(e.message)).finally(()=>setAbortBusy(false));}
 function points(values:number[],height:number){if(values.length<2)return '';const min=Math.min(...values),max=Math.max(...values),span=max-min||1;return values.map((v,i)=>`${i/(values.length-1)*100},${height-(v-min)/span*height}`).join(' ')}
 const abortEnabled=!!runtime&&runtime.status==='RUNNING'&&ABORTABLE.has(runtime.state)&&!abortBusy;
 return <main><header><div><p className="eyebrow">ADAPTIVE RADIAL PULSE · D3</p><h1>自动施压安全数字仿真</h1><p>设备状态机 → 安全监督 → 故障矩阵 → 可重放报告</p></div><div className="statusGroup"><span className="status">{health}</span><span className="status">{device}</span></div></header>
 <section className="controls d3Controls"><div><h2>D3正常Profile运行</h2><p>启动会话 · 设备侧状态机 · ABORT→RETRACT→卸载 · 合成相对单位，非人体安全验证</p></div><div className="buttonRow"><button onClick={startRuntime} disabled={runtimeBusy}> {runtimeBusy?'运行中…':'启动正常Profile'} </button><button className="danger" onClick={abortRuntime} disabled={!abortEnabled}>{abortBusy?'ABORT中…':'ABORT'}</button></div></section>
 {runtime&&<><section className="metrics"><article><small>运行状态</small><strong>{runtime.status}</strong></article><article><small>设备状态</small><strong>{runtime.state}</strong></article><article><small>目标载荷</small><strong>{runtime.target_force_au??'—'} au</strong></article><article><small>实际载荷</small><strong>{runtime.actual_force_au.toFixed(2)} au</strong></article><article><small>位移</small><strong>{runtime.position_au.toFixed(3)} au</strong></article><article><small>控制命令</small><strong>{runtime.command.toFixed(3)}</strong></article><article><small>当前 tick</small><strong>{runtime.tick}</strong></article><article><small>卸载完成</small><strong>{runtime.unload_complete?'是':'否'}</strong></article></section>
 <section><div className="sectionHeading"><div><h2>运行状态时间线</h2><p>最终状态：{runtime.final_state??'进行中'} · run {runtime.run_id.slice(0,8)}</p></div></div><div className="timeline">{runtime.timeline.map(item=><article key={`t-${item.tick}-${item.state}`}><div className="tick">T{item.tick}</div><div><h3>{item.state}</h3></div></article>)}</div>
 <div className="sectionHeading" style={{marginTop:18}}><div><h2>安全与ABORT事件</h2><p>事件来自设备侧会话，前端不伪造状态</p></div></div><div className="timeline">{runtime.events.length?runtime.events.map((event,i)=><article key={`e-${event.tick}-${i}`}><div className="tick">T{event.tick}</div><div><h3>{event.type}{event.code?` · ${event.code}`:''}</h3><p>{event.action?`${event.action} → `:''}{event.state??''}</p>{typeof event.command==='number'&&<small>命令 {event.command.toFixed(2)}</small>}</div></article>):<p>尚无事件</p>}</div>
 <footer>{runtime.disclaimer}</footer></section></>}
 <section className="controls d3Controls"><div><h2>D3安全故障矩阵</h2><p>14类冻结场景 · 相对单位 · 非人体安全验证</p></div><button onClick={runD3} disabled={d3Busy}>{d3Busy?'运行中…':'运行D3矩阵'}</button></section>
 {d3&&<><section className="metrics"><article><small>矩阵结果</small><strong>{d3.summary.all_passed?'全部通过':'存在失败'}</strong></article><article><small>通过场景</small><strong>{d3.summary.passed_count}/{d3.summary.case_count}</strong></article><article><small>分析权限</small><strong>{d3.analysis_allowed?'允许':'阻断'}</strong></article><article><small>报告摘要</small><strong>{d3.report_sha256.slice(0,8)}</strong></article></section>
 <section><div className="sectionHeading"><div><h2>安全事件时间线</h2><p>按设备tick记录主故障、动作、目标状态与检测延迟</p></div><button className="secondary" onClick={replayD3}>确定性重放</button></div><p className="replayState">重放状态：{replayState}</p><div className="timeline">{d3.events.map(event=><article key={event.case_id}><div className="tick">T{event.event_tick}</div><div><h3>{event.case_id}</h3><p><b>{event.fault}</b> → {event.action} → {event.state}</p><small>检测延迟 {event.detection_latency_ticks} tick · 命令 {event.command.toFixed(2)}</small></div></article>)}</div><footer>{d3.disclaimer}</footer></section></>}
 <section className="controls"><div><h2>D2合成工程实验</h2><p>force_au · 仿射标定 · 40/80/120相对平台</p></div><button onClick={runD2} disabled={d2Busy}>{d2Busy?'实验中…':'运行D2实验'}</button></section>
 {d2&&<><section className="metrics"><article><small>标定</small><strong>{d2.calibration_id}</strong></article><article><small>分析门控</small><strong>{d2.analysis_allowed?'通过':'阻断'}</strong></article><article><small>候选平台</small><strong>{d2.best_target_force_au??'—'} au</strong></article><article><small>报告摘要</small><strong>{d2.report_sha256.slice(0,8)}</strong></article></section><section><h2>D2压力步骤</h2><div className="steps">{d2.steps.map(s=><article key={`${s.step_index}-${s.target_force_au}`}><h3>{s.target_force_au} au</h3><p>质量：{s.quality_label}</p><p>稳态样本：{s.stable_sample_count}</p><p>评分：{s.score?.toFixed(3)??'已阻断'}</p></article>)}</div><footer>{d2.disclaimer}</footer></section></>}
 <section className="controls"><div><h2>模拟会话</h2><p>250 Hz · 72 bpm · 三个研究用载荷平台</p></div><button onClick={run} disabled={busy}>{busy?'采集中…':'开始模拟采集'}</button></section>
 {wave.length>1&&<section><h2>实时数据</h2><p>脉搏通道</p><svg className="chart" viewBox="0 0 100 50" preserveAspectRatio="none"><polyline points={points(wave,50)}/></svg><p>载荷通道</p><svg className="chart force" viewBox="0 0 100 50" preserveAspectRatio="none"><polyline points={points(force,50)}/></svg></section>}
 {error&&<p className="error">{error}</p>}{result&&<><section className="metrics"><article><small>有效分析</small><strong>{result.report.analysis_allowed?'通过':'阻断'}</strong></article><article><small>完整帧</small><strong>{result.manifest.statistics.frame_count}</strong></article><article><small>丢帧</small><strong>{result.manifest.statistics.missing_frame_count}</strong></article><article><small>最佳模拟载荷（相对值）</small><strong>{result.report.best_target_force===null?'—':result.report.best_target_force/1000}</strong></article></section>
 <section><h2>各载荷平台结果</h2><div className="steps">{result.report.steps.map(s=><article key={s.target_force}><div className="bar" style={{height:`${Math.max(10,(s.pulse_amplitude??0)/2000)}px`}}/><h3>{s.target_force/1000}</h3><p>质量：{s.quality_label}</p><p>心率：{s.heart_rate_bpm?.toFixed(1)??'已阻断'} bpm</p></article>)}</div></section><footer>{result.report.disclaimer}</footer></>}
 {!result&&!runtime&&!d3&&<section className="empty"><div className="pulse">∿</div><h2>尚未生成会话</h2><p>启动模拟后将显示数据完整性、质量门控和压力响应。</p></section>}</main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
